version: '3.3'
services:
  opencartdb:
    image: mariadb
    container_name: opencart${OPENCART_VER}_db
    volumes:
     - ./mysql:/var/lib/mysql
    ports:
     - "3306"
#    restart: always
    environment:
     - MYSQL_DATABASE=opencart
     - MYSQL_ROOT_PASSWORD=123

  opencartweb:
#    image: rtakauti/ci-opencart3.0.2.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OPENCART_VER=${OPENCART_VER}
        - OPENCART_URL=${OPENCART_URL}
    container_name: opencart${OPENCART_VER}_web
    depends_on:
    - opencartdb
    volumes:
    - ./html:/var/www/html
    - ./:/var/www
    ports:
    - "80"
    links:
    - opencartdb:mysql
#    restart: always
    environment:
    - VIRTUAL_HOST=opencart.local
    - APACHE_DOC_ROOT=/var/www/html
    - XDEBUG_ENABLE=1
    - PHP_TIMEZONE=America/Sao_Paulo

networks:
  default:
    external:
      name: webproxy

